In [4]:
import pandas as pd 

df = pd.read_csv("../dataset/personal-finance-dataset.csv")

In [5]:
df.head()

,date,user_id,monthly_income,monthly_expense_total,savings_rate,budget_goal,financial_scenario,credit_score,debt_to_income_ratio,loan_payment,...,discretionary_spending,essential_spending,income_type,rent_or_mortgage,category,cash_flow_status,financial_advice_score,financial_stress_level,actual_savings,savings_goal_met
0,2019-01-01,1584,3119.58,3212.07,0.38,3676.11,inflation,721.0,0.56,125.77,...,857.55,1910.85,Freelance,1501.65,Investments,Positive,8.3,Low,0.00,0
1,2019-01-31,1045,3262.44,3732.81,0.10,2607.17,inflation,670.0,0.42,454.19,...,534.51,3165.20,Salary,1603.17,Investments,Positive,22.6,Low,0.00,0
2,2019-03-02,1756,2931.20,3335.58,0.15,3004.14,inflation,691.0,0.24,971.82,...,353.67,1504.56,Freelance,1097.82,Healthcare,Positive,58.8,Low,0.00,0
3,2019-04-01,1724,3506.79,2327.59,0.17,3346.97,normal,717.0,0.16,482.76,...,594.08,1450.72,Freelance,1155.64,Groceries,Positive,74.5,Low,1179.20,0
4,2019-05-01,1600,4606.87,2182.58,0.34,2670.09,inflation,795.0,0.25,263.74,...,556.86,1000.00,Salary,1170.86,Utilities,Negative,38.7,High,2424.29,0

In [8]:
df.shape

(3000, 25)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   date                    3000 non-null   object
 1   user_id                 3000 non-null   int64
 2   monthly_income          3000 non-null   float64
 3   monthly_expense_total   3000 non-null   float64
 4   savings_rate            3000 non-null   float64
 5   budget_goal             3000 non-null   float64
 6   financial_scenario      3000 non-null   object
 7   credit_score            3000 non-null   float64
 8   debt_to_income_ratio    3000 non-null   float64
 9   loan_payment            3000 non-null   float64
 10  investment_amount       3000 non-null   float64
 11  subscription_services   3000 non-null   int64
 12  emergency_fund          3000 non-null   float64
 13  transaction_count       3000 non-null   int64
 14  fraud_flag              3000 non-null   int64
 15  discretionary_spending  3000 non-null   float64
 16  essential_spending      3000 non-null   float64
 17  income_type             3000 non-null   object
 18  rent_or_mortgage        3000 non-null   float64
 19  category                3000 non-null   object
 20  cash_flow_status        3000 non-null   object
 21  financial_advice_score  3000 non-null   float64
 22  financial_stress_level  3000 non-null   object
 23  actual_savings          3000 non-null   float64
 24  savings_goal_met        3000 non-null   int64
dtypes: float64(14), int64(5), object(6)
memory usage: 586.1+ KB

In [14]:
df.describe()

,user_id,monthly_income,monthly_expense_total,savings_rate,budget_goal,credit_score,debt_to_income_ratio,loan_payment,investment_amount,subscription_services,emergency_fund,transaction_count,fraud_flag,discretionary_spending,essential_spending,rent_or_mortgage,financial_advice_score,actual_savings,savings_goal_met
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.00000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,1498.699000,4004.267347,3011.682230,0.225897,2811.070463,679.923667,0.350817,508.58113,400.610493,4.975000,1005.349830,59.529333,0.023667,500.810990,2215.587100,1211.897797,50.071133,1156.418457,0.092333
std,287.352782,1000.107096,801.151864,0.101417,490.855344,49.970847,0.145191,199.44458,235.361273,2.559536,485.780881,23.101610,0.152034,199.800377,596.267983,400.482024,29.087360,1039.597384,0.289544
min,1000.000000,685.280000,159.210000,0.050000,1175.570000,515.000000,0.100000,0.00000,0.000000,1.000000,0.000000,20.000000,0.000000,0.000000,1000.000000,300.000000,0.100000,0.000000,0.000000
25%,1248.750000,3362.250000,2473.205000,0.140000,2481.957500,646.000000,0.220000,375.34000,234.780000,3.000000,674.012500,38.750000,0.000000,361.562500,1807.235000,933.530000,25.100000,144.965000,0.000000
50%,1496.500000,4008.075000,3023.810000,0.230000,2822.285000,679.000000,0.350000,508.57000,388.075000,5.000000,1010.485000,60.000000,0.000000,496.340000,2215.705000,1213.605000,48.700000,1032.810000,0.000000
75%,1749.000000,4659.040000,3555.502500,0.310000,3131.000000,713.000000,0.480000,638.47000,559.842500,7.000000,1337.820000,79.000000,0.000000,640.105000,2624.675000,1482.860000,76.100000,1821.510000,0.000000
max,1999.000000,7407.940000,5853.200000,0.400000,4386.500000,847.000000,0.600000,1176.88000,1292.300000,9.000000,2585.360000,99.000000,1.000000,1158.740000,4245.900000,2614.620000,100.000000,6589.660000,1.000000

In [15]:
df.isnull().sum()

date                      0
user_id                   0
monthly_income            0
monthly_expense_total     0
savings_rate              0
budget_goal               0
financial_scenario        0
credit_score              0
debt_to_income_ratio      0
loan_payment              0
investment_amount         0
subscription_services     0
emergency_fund            0
transaction_count         0
fraud_flag                0
discretionary_spending    0
essential_spending        0
income_type               0
rent_or_mortgage          0
category                  0
cash_flow_status          0
financial_advice_score    0
financial_stress_level    0
actual_savings            0
savings_goal_met          0
dtype: int64

In [20]:
df.nunique()

date                        60
user_id                    944
monthly_income            2985
monthly_expense_total     2983
savings_rate                36
budget_goal               2967
financial_scenario           3
credit_score               264
debt_to_income_ratio        51
loan_payment              2925
investment_amount         2785
subscription_services        9
emergency_fund            2910
transaction_count           80
fraud_flag                   2
discretionary_spending    2912
essential_spending        2911
income_type                  3
rent_or_mortgage          2927
category                    10
cash_flow_status             3
financial_advice_score     952
financial_stress_level       3
actual_savings            2342
savings_goal_met             2
dtype: int64

In [21]:
df["category"].value_counts()

category
Insurance         321
Utilities         320
Healthcare        308
Groceries         308
Dining Out        306
Transportation    305
Entertainment     291
Education         289
Investments       286
Rent              266
Name: count, dtype: int64

In [22]:
df["cash_flow_status"].value_counts()

cash_flow_status
Positive    1783
Neutral      621
Negative     596
Name: count, dtype: int64

In [23]:
df["financial_scenario"].value_counts()

financial_scenario
normal       1739
inflation     648
recession     613
Name: count, dtype: int64

In [26]:
df.columns

Index(['date', 'user_id', 'monthly_income', 'monthly_expense_total',
       'savings_rate', 'budget_goal', 'financial_scenario', 'credit_score',
       'debt_to_income_ratio', 'loan_payment', 'investment_amount',
       'subscription_services', 'emergency_fund', 'transaction_count',
       'fraud_flag', 'discretionary_spending', 'essential_spending',
       'income_type', 'rent_or_mortgage', 'category', 'cash_flow_status',
       'financial_advice_score', 'financial_stress_level', 'actual_savings',
       'savings_goal_met'],
      dtype='object')